### ISSUE TITLE
the legup hls compiler

### ISSUE THREAD

**Issue by Wuyoo0203** [MicrochipTech/fpga-hls-examples#43]
Hello, where can I find the original repository of the legup hls compiler iteself?

**Comment by duc-tran-mchp** [comment]
Hi, LegUp Computing Inc. has been acquired by Microchip Technology and is now part of the FPGA design tools as SmartHLS.
https://www.microchip.com/en-us/products/fpgas-and-plds/fpga-and-soc-design-tools/smarthls-compiler
For the academic open-source version, please refer to http://legup.eecg.utoronto.ca./
